urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib import admin
from djangoratings.views import AddRatingFromModel
from views import CommentListView, WallListView

from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap

from blog.models import Post, Blog, Category
from user_groups.models import Group
from profiles.models import Profile

post_dict = {
    'queryset': Post.objects.published(),
    'date_field': 'publish',
    }

blog_dict = {
    'queryset': Blog.objects.filter(is_delete = False),
    'date_field': 'modified',
    }

club_dict = {
    'queryset': Group.objects.filter(is_active = True),
    'date_field': 'modified',
    }

cat_dict = {
    'queryset': Category.objects.all(),
    }

user_dict = {
    'queryset': Profile.objects.filter(user__is_active = True),
    }


sitemaps = {
    'post': GenericSitemap(post_dict, priority=0.6),
    'blog': GenericSitemap(blog_dict, priority=0.5),
    'cat': GenericSitemap(cat_dict, priority=0.6),
    'club': GenericSitemap(club_dict, priority=0.7),
    'user': GenericSitemap(user_dict, priority=0.7),
    }

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', 'views.index'),

    url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    
    url(r'^barwiki/', include('wakawaka.urls')),

    url(r'^blogs/', include('blog.urls')),
    url(r'^clubs/', include('user_groups.urls')),

    url(r'^comment/posted/$', 'blog.views.comment_posted' ),
    url(r'^comment/', include('django.contrib.comments.urls')),

    url(r'^wall/', include('wall.urls')),
	
	url(r'^search/', include('haystack.urls')),

    url(r'^u/', include('userena.urls')),
    url(r'^msg/', include('userena.contrib.umessages.urls')),
    url(r'^relation/', include('relationships.urls')),


    url(r'^admin/', include(admin.site.urls)),

    url(r'^invite/', include('invitations.urls'), ),

    url(r'^comments/$', CommentListView.as_view(), name='comments_all'),
    url(r'^comments/page-(?P<page>\d+)/$', CommentListView.as_view(), name='comments_all_paginated'),

    url(r'^walls/$', WallListView.as_view(), name='wall_items_all'),
    url(r'^walls/page-(?P<page>\d+)/$', WallListView.as_view(), name='wall_items_all_paginated'),

)

urlpatterns += patterns('',
    url(r'api/ratecomment/(?P<object_id>\d+)/(?P<score>[-\d]+)/', AddRatingFromModel(), {
        'app_label': 'threadedcomments',
        'model': 'threadedcomment',
        'field_name': 'rating',
        }),
    url(r'api/ratewall/(?P<object_id>\d+)/(?P<score>[-\d]+)/', AddRatingFromModel(), {
        'app_label': 'wall',
        'model': 'wallitem',
        'field_name': 'rating',
        }),
    url(r'api/ratepost/(?P<object_id>\d+)/(?P<score>[-\d]+)/', AddRatingFromModel(), {
        'app_label': 'blog',
        'model': 'post',
        'field_name': 'rating',
        }),
    url(r'api/favepost/(?P<object_id>\d+)/(?P<score>[-\d]+)/', AddRatingFromModel(), {
        'app_label': 'blog',
        'model': 'post',
        'field_name': 'favorite',
        }),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^m/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

userena/urls.py
from django.conf.urls.defaults import *
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from userena import views as userena_views
from userena import settings as userena_settings

urlpatterns = patterns('',
    # Signup, signin and signout
#    url(r'^signup/$',
#       userena_views.signup,
#       name='userena_signup'),
    url(r'^login/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^logout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt'},
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

    # Signup
    url(r'^(?P<username>[\.\w]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^(?P<username>[\.\w]+)/activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w]+)/disabled/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w]+)/page-(?P<page>[0-9]+)/$',
        userena_views.profile_detail,
        name='userena_profile_detail'),
    url(r'^page-(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

wall/models.py
import datetime, markdown
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from djangoratings.fields import VotingField

class WallItem(models.Model):
    content_type = models.ForeignKey(ContentType,
        verbose_name=_('content type'),
        related_name="content_type_set_for_%(class)s")
    object_pk = models.TextField(_('object ID'))
    content_object = generic.GenericForeignKey(ct_field="content_type", fk_field="object_pk")

    # Metadata about the comment
    site = models.ForeignKey(Site)

    user = models.ForeignKey(User, verbose_name=_('user'),
        blank=True, null=True, related_name="%(class)s_wallitems")
    submit_date = models.DateTimeField(_('date/time submitted'), default=None)
    is_removed = models.BooleanField(_('is removed'), default=False,
        help_text=_('Check this box if the comment is inappropriate. '\
                    'A "This comment has been removed" message will '\
                    'be displayed instead.'))

    body = models.TextField(_('body'))
    body_html = models.TextField(_('body'))

    rating = VotingField()

    def save(self, *args, **kwargs):
        html = markdown.markdown(self.body, extensions=['nl2br', ])
        self.body_html = html

        super(WallItem, self).save(*args, **kwargs)


    class Meta:
        permissions = [("can_moderate", "Can moderate wall")]
        verbose_name = _('wall')
        verbose_name_plural = _('walls')
        ordering = ['-submit_date',]

    def get_editable(self):
        week = datetime.datetime.now() - datetime.timedelta(days=7)
        if self.submit_date >= week:
            return True
        else:
            return False

wall/forms.py
from django.utils import timezone
from django import forms
from django.contrib.comments.forms import CommentSecurityForm
from django.contrib.contenttypes.models import ContentType
from django.utils.encoding import force_unicode
import settings
from wall.models import WallItem
from django.utils.translation import ugettext_lazy as _

class AddWallItem(CommentSecurityForm):

    def __init__(self, target_object, parent=None, data=None, initial=None):
        if initial is None:
            initial = {}
        super(AddWallItem, self).__init__(target_object, data=data,
            initial=initial)

    comment       = forms.CharField(label=_('Comment'), widget=forms.Textarea)

    honeypot      = forms.CharField(required=False,
        label=_('If you enter anything in this field '\
                'your comment will be treated as spam'))

    def clean_honeypot(self):
        value = self.cleaned_data["honeypot"]
        if value:
            raise forms.ValidationError(self.fields["honeypot"].label)
        return value

    def get_comment_object(self):
        """
        Return a new (unsaved) comment object based on the information in this
        form. Assumes that the form is already validated and will throw a
        ValueError if not.

        Does not set any of the fields that would come from a Request object
        (i.e. ``user`` or ``ip_address``).
        """
        if not self.is_valid():
            raise ValueError("get_comment_object may only be called on valid forms")

        CommentModel = self.get_comment_model()
        new = CommentModel(**self.get_comment_create_data())
        new = self.check_for_duplicate_comment(new)

        return new

    def get_comment_create_data(self):
        """
        Returns the dict of data to be used to create a comment. Subclasses in
        custom comment apps that override get_comment_model can override this
        method to add extra fields onto a custom comment model.
        """
        return dict(
            content_type = ContentType.objects.get_for_model(self.target_object),
            object_pk    = force_unicode(self.target_object._get_pk_val()),
            body         = self.cleaned_data["comment"],
            submit_date  = timezone.now(),
            site_id      = settings.SITE_ID,
        )

    def check_for_duplicate_comment(self, new):
        """
        Check that a submitted comment isn't a duplicate. This might be caused
        by someone posting a comment twice. If it is a dup, silently return the *previous* comment.
        """
        possible_duplicates = self.get_comment_model()._default_manager.using(
            self.target_object._state.db
        ).filter(
            content_type = new.content_type,
            object_pk = new.object_pk,
        )
        for old in possible_duplicates:
            if old.submit_date.date() == new.submit_date.date() and old.body == new.body:
                return old

        return new

    def get_comment_model(self):
        return WallItem

templates/groups/base_groups.html
{% extends "base-1c.html" %}

{% block title %}{% if group %}{{ group.title }}{% else %}Клубы{% endif %}{% endblock %}
{% block li-groups %}active{% endblock %}

{% block content_title %}
  {% load groups %}
  <h1><a href="{{ group.get_absolute_url }}">{{ group }}</a> {% block group_title %}{% endblock %}</h1>
{% endblock %}

templates/groups/group_detail.html
{% extends "groups/base_groups.html" %}


{% block title %}{{ group }}{% endblock %}

{% block content %}
  {% load groups markup thumbnail guardian_tags wall_tags pagination %}
  {% get_obj_perms user for group as "group_perm" %}

    <div class="row-fluid">
        <div class="span4">
            <div class="group_icon">
                {% if group.icon %}
                    <img src="{% thumbnail group.icon 300x0 %}" class="profileicon" />
                {% endif %}
            </div>
            <p><b>Администратор клуба</b></p>
            <p>
                <img src="{% thumbnail group.creator.profile.mugshot 20x20 %}" class="profileicon" />
                <a href='{% url userena_profile_detail group.creator.username %}'>{% if group.creator.get_full_name %}{{group.creator.get_full_name}}{% else %}{{ group.creator.get_full_name }}{% endif %}</a>
            </p>
            {% if member_list %}
                <p><b>Участники клуба</b></p>
                <p>
                {% for member in member_list %}
                    <a href='{% url userena_profile_detail member.user.username %}'>{% if member.user.get_full_name %}{{member.user.get_full_name}}{% else %}{{ member.user.username }}{% endif %}</a>{%  if not forloop.last %},{% endif %}
                {% endfor %}
                </p>
            {% endif %}
            {% if user.is_authenticated %}
                <hr/>
                {% if group|is_member:user %}
                    {% if not group|is_owner:user %}
                        <p><a href="{% url left_group group.slug %}">Покинуть клуб</a></p>
                    {% endif %}
                {% else %}
                    <p><a href="{% url join_group group.slug %}">Вступить в клуб</a></p>
                {% endif %}
                {% if "change_group" in group_perm %}
                    <p><a href="{% url edit_group group.slug %}">Редактировать</a></p>
                    <p><a href="{% url remove_group group.slug %}">Удалить</a></p>
                {% endif %}
            {% endif %}
            {% if linkexchange_blocks.0 != '<!--1219604906152-->' %}<hr/><div class="well well-small" >
                {{linkexchange_blocks.0|safe}}
            </div>{% endif %}
        </div>
        <div class="span8">

            {% if group.tease %}
                <div class="well">
                    {{ group.tease|markdown }}
                </div>
            {% endif %}

            <div class="row-fluid">
                {% if topic_list %}
                    <div class="span6">
                        <p><b>Последние посты</b></p>
                        <p><ul>
                        {% for topic in topic_list %}
                            <li><a href="{{ topic.get_absolute_url }}" title="{{ topic.title }}" >{{ topic.title }}</a></li>
                        {% empty %}
                            <li>Никто еще ничего не написал.</li>
                        {% endfor %}
                    </ul></p>
                    </div>
                {% endif %}


                {% if group_blog_list %}
                    <div class="span6">
                        <p><b>Блоги клуба</b></p>
                        <p><ul>
                        {% for blog in group_blog_list %}
                            <li><a href="{{ blog.get_absolute_url }}" title="перейти в блог">{{ blog.title }}</a></li>
                        {% endfor %}
                        </ul></p>
                    </div>
                {% endif %}

            </div>
            <hr/>

            {% get_wallitem_list for group as wallitem_list %}
            {% autopaginate wallitem_list %}

        {% if user.is_authenticated %}
            {% get_wallitem_form for group as wall_form %}


            <form action="{% url wall-post-comment %}" class="form-horizontal" method="post">{% csrf_token %}
                <input type="hidden" name="next" value="{{ group.get_absolute_url }}">
                {% for field in wall_form %}
                    {% if not field.is_hidden %}
                        <div class="control-group{% if field.errors %} error{% endif %}" id="fiels_{{ field.html_name }}">
                            {{ field }}
                            {% if field.help_text %}
                                <p class="help-block">{{ field.help_text|safe }}</p>
                            {% endif %}
                            {% if field.errors %}
                                <span class="help-inline">{{ field.errors }}</span>
                            {% endif %}
                        </div>
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %}
                <input type="submit" name="post" value="Отправить" class="btn btn-success" />
            </form>

        {% endif %}

            {% for item in wallitem_list %}
                {% include 'wall.html' with comment=item %}
            {% empty %}
                <p>Никто ничего не писал.</p>
            {% endfor %}

            {% if page_obj.has_other_pages %}
                {% with group.get_absolute_url as baseurl %}
                    {% include "_pagination.html" with baseurl=baseurl %}
                {% endwith %}
            {% endif %}

        </div>
    </div>

{% endblock %}

{% block js %}
    {% if user.is_authenticated %}
    <script type="text/javascript" src="http://yandex.st/jquery/form/3.09/jquery.form.min.js"></script>
    <script type="text/javascript" >

        $('#ajaxform input').change(function() {
            $('#ajaxform').ajaxSubmit({
                success: showResponse,
                dataType:'json'
            });
            return false;
        });

        function showResponse(data)  {
            if (data.status == 'error') {
                alert (data.message);
            } else {
                txt = '<div class="comment_img"><img src="' + data.files[0]['thumb_url'] + '" />';
                txt += '<a class="add_img_to_c" href="#" data-url="' + data.files[0]['original_url'] + '">вставить</a>';
                txt += '<a class="del_img_to_c" href="#" data-url="' + data.files[0]['original_url'] + '" data-del="' + data.files[0]['delete_link'] + '">x</a>';
                txt += '</div>';
                $('#userfiles').prepend(txt);
                $('#ajaxform input[type="file"]').attr('value', '');
            };
        }

        $('#userfiles .add_img_to_c').live('click', function(event) {
            event.preventDefault();
            var url = $(this).attr('data-url');
            $('#id_comment').insertAtCaret("!["+url+"]("+url+")");
        })

        var commentdiv = false;

        $('#userfiles .del_img_to_c').live('click', function(event) {
            event.preventDefault();
            var url = $(this).attr('data-url');
            window.commentdiv = $(this).parent();
            $.getJSON($(this).attr('data-del'), function(data) {
                if (data.status == 'error') {
                    alert(data.message);
                } else {
                    window.commentdiv.remove();
                };
            });
        })

    </script>
    {% endif %}
{% endblock %}

templates/groups/group_form.html
{% extends "groups/base_groups.html" %}


{% block title %}{% if group %}Edit{% else %}Create a{% endif %} group{% endblock %}
{% block body_class %}{{ block.super }} group_form{% endblock %}


{% block content_title %}
  <h2>{% if group %}Edit{% else %}Create a{% endif %} group</h2>
{% endblock %}


{% block content %}
  {% load stringutils %}
<form action=".{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}" method="post" autocomplete="off" enctype="multipart/form-data" class="form-horizontal">
  {% csrf_token %}
    {% for field in form %}
        {% include 'field.html' %}
    {% endfor %}
    <div class="form-actions">
        <input type="submit" value="Сохранить" class="btn btn-primary" />
        <a href="{{group.get_absolute_url}}" class="btn">Отмена</a>
    </div>
</form>
{% endblock %}

templates/groups/group_invite.html
{% extends "base.html" %}


{% block title %}Group invite{% endblock %}
{% block body_class %}{{ block.super }} groups group_invite{% endblock %}


{% block content_title %}
  <h2>Group invite</h2>
{% endblock %}


{% block content %}
  {% load stringutils %}

  <form action="." method="post">{% csrf_token %}
    {{ form|format_fields }}
    <p class="submit"><button type="submit">Send</button></p>
  </form>
{% endblock %}

templates/groups/group_join_confirm.html
{% extends "groups/base_groups.html" %}


{% block title %}Join group{% endblock %}
{% block body_class %}{{ block.super }} group_confirm_join{% endblock %}


{% block content_title %}
  <h2>Join {{ group }}</h2>
{% endblock %}


{% block content %}
  <form action=".{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}" method="post">{% csrf_token %}
    <p>Are you sure you want to join the group, "{{ group }}?"</p>
    <p class="submit"><button type="submit">Indeed</button></p>
  </form>
{% endblock %}

templates/groups/group_left_confirm.html
{% extends "groups/base_groups.html" %}

{% block title %}Покинуть клуб{% endblock %}

{% block content_title %}
    <h2>Покинуть клуб: {{ group }}</h2>
{% endblock %}


{% block content %}
    <form action=".{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}" method="post">{% csrf_token %}
        <p>Вы действительно хотите покинуть клуб "{{ group }}?"</p>
        <p class="submit"><button type="submit">Покинуть клуб</button></p>
    </form>
{% endblock %}

templates/groups/group_list.html
{% extends "base.html" %}

{% block li-groups %}active{% endblock %}

{% load thumbnail pymorphy_tags %}

{% block title %}Список клубов{% endblock %}

{% block content_title %}
  <h2>Список клубов</h2>
{% endblock %}


{% block content %}
    {% if user.is_authenticated %}
        <div class="pull-right"><a class="btn" href="{% url create_group %}">Создать группу</a></div>
    {% endif %}

    <ul class="nav nav-tabs" id="grouptabbed">
        <li class="active"><a href="#all" data-toggle="tab">Все клубы</a></li>
        <li><a href="#mine" data-toggle="tab">Мои клубы</a></li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane active" id="all">
        {% if group_list %}
            {% for group in group_list %}
                <div class="group">
                    {% if group.icon %}
                        <img src="{{group.icon|thumbnail_url:'group_small'}}" class="groupicon" />
                    {% endif %}
                    <h5><a href="{{ group.get_absolute_url }}">{{ group }}</a></h5>
                    {{ group.group_blog.count }}
                    {{ "блог"|plural:group.group_blog.count }},
                    {{ group.members.count }}
                    {{ "участник"|plural:group.members.count }}
                    <div class="clearfix"></div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="tab-pane" id="mine">
          {% for group in membership_list %}
              <div class="group">
                  {% if group.icon %}
                      <img src="{{group.icon|thumbnail_url:'group_small'}}" class="groupicon" />
                  {% endif %}
                  <h5><a href="{{ group.get_absolute_url }}">{{ group }}</a></h5>
                  {{ group.group_blog.count }}
                  {{ "блог"|plural:group.group_blog.count }},
                  {{ group.members.count }}
                  {{ "участник"|plural:group.members.count }}
                  <div class="clearfix"></div>
              </div>
          {% empty %}
              <p>Вы не состоите ни в одном клубе.</p>
          {% endfor %}
    </div>
</div>
{% endblock %}

templates/groups/group_members.html
{% extends "groups/base_groups.html" %}


{% block title %}Members{% endblock %}
{% block body_class %}{{ block.super }} group_members{% endblock %}


{% block group_title %}/ Members{% endblock %}


{% block content %}
  {% load groups %}

  {% if member_list %}
    <ul>
      {% for member in member_list %}
        <li><a href='{% url userena_profile_detail member.user.username %}'>{% if member.user.get_full_name %}{{member.user.get_full_name}}{% else %}{{ member.user.username }}{% endif %}</a></li>
      {% endfor %}
    </ul>
  {% endif %}

  {% if user and group|is_member:user %}
    <p><a class="button" href="{% url invite group.slug %}?next={{ request.path }}">Invite someone</a></p>
  {% endif %}
{% endblock %}

templates/groups/group_remove_confirm.html
{% extends "groups/base_groups.html" %}


{% block title %}Group delete confirmation{% endblock %}
{% block body_class %}{{ block.super }} group_confirm_delete{% endblock %}


{% block content_title %}
  <h2>Group delete confirmation</h2>
{% endblock %}


{% block content %}
  <form action=".{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}" method="post">{% csrf_token %}
    <p>Are you sure you want to delete the group "{{ group }}?"</p>
    <p class="submit"><button type="submit">Indeed</button></p>
  </form>
{% endblock %}