urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib import admin
from djangoratings.views import AddRatingFromModel
from views import CommentListView, WallListView

from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap

from blog.models import Post, Blog, Category
from user_groups.models import Group
from profiles.models import Profile

post_dict = {
    'queryset': Post.objects.published(),
    'date_field': 'publish',
    }

blog_dict = {
    'queryset': Blog.objects.filter(is_delete = False),
    'date_field': 'modified',
    }

club_dict = {
    'queryset': Group.objects.filter(is_active = True),
    'date_field': 'modified',
    }

cat_dict = {
    'queryset': Category.objects.all(),
    }

user_dict = {
    'queryset': Profile.objects.filter(user__is_active = True),
    }


sitemaps = {
    'post': GenericSitemap(post_dict, priority=0.6),
    'blog': GenericSitemap(blog_dict, priority=0.5),
    'cat': GenericSitemap(cat_dict, priority=0.6),
    'club': GenericSitemap(club_dict, priority=0.7),
    'user': GenericSitemap(user_dict, priority=0.7),
    }

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', 'views.index'),

    url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    
    url(r'^barwiki/', include('wakawaka.urls')),

    url(r'^blogs/', include('blog.urls')),
    url(r'^clubs/', include('user_groups.urls')),

    url(r'^comment/posted/$', 'blog.views.comment_posted' ),
    url(r'^comment/', include('django.contrib.comments.urls')),

    url(r'^wall/', include('wall.urls')),
	
	url(r'^search/', include('haystack.urls')),

    url(r'^u/', include('userena.urls')),
    url(r'^msg/', include('userena.contrib.umessages.urls')),
    url(r'^relation/', include('relationships.urls')),


    url(r'^admin/', include(admin.site.urls)),

    url(r'^invite/', include('invitations.urls'), ),

    url(r'^comments/$', CommentListView.as_view(), name='comments_all'),
    url(r'^comments/page-(?P<page>\d+)/$', CommentListView.as_view(), name='comments_all_paginated'),

    url(r'^walls/$', WallListView.as_view(), name='wall_items_all'),
    url(r'^walls/page-(?P<page>\d+)/$', WallListView.as_view(), name='wall_items_all_paginated'),

)

urlpatterns += patterns('',
    url(r'api/ratecomment/(?P<object_id>\d+)/(?P<score>[-\d]+)/', AddRatingFromModel(), {
        'app_label': 'threadedcomments',
        'model': 'threadedcomment',
        'field_name': 'rating',
        }),
    url(r'api/ratewall/(?P<object_id>\d+)/(?P<score>[-\d]+)/', AddRatingFromModel(), {
        'app_label': 'wall',
        'model': 'wallitem',
        'field_name': 'rating',
        }),
    url(r'api/ratepost/(?P<object_id>\d+)/(?P<score>[-\d]+)/', AddRatingFromModel(), {
        'app_label': 'blog',
        'model': 'post',
        'field_name': 'rating',
        }),
    url(r'api/favepost/(?P<object_id>\d+)/(?P<score>[-\d]+)/', AddRatingFromModel(), {
        'app_label': 'blog',
        'model': 'post',
        'field_name': 'favorite',
        }),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^m/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

userena/urls.py
from django.conf.urls.defaults import *
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from userena import views as userena_views
from userena import settings as userena_settings

urlpatterns = patterns('',
    # Signup, signin and signout
#    url(r'^signup/$',
#       userena_views.signup,
#       name='userena_signup'),
    url(r'^login/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^logout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt'},
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

    # Signup
    url(r'^(?P<username>[\.\w]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^(?P<username>[\.\w]+)/activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w]+)/disabled/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w]+)/page-(?P<page>[0-9]+)/$',
        userena_views.profile_detail,
        name='userena_profile_detail'),
    url(r'^page-(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

wall/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('wall.views',
    url(r'^post/$',          'wall_comment',       name='wall-post-comment'),
    url(r'^w/edit/(?P<comment_id>[\d]+)/$',
        'edit_item',
        name='wall_edit_comment'
    ),
    url(r'^w/del/(?P<comment_id>[\d]+)/$',
        'del_item',
        name='wall_del_comment'
    ),
)

blog/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.utils.hashcompat import sha_constructor
from django.db import models
from django.conf import settings
from django.db.models import permalink
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _

from blog.managers import PublicManager
from tagging.fields import TagField
from user_groups.models import Group

import datetime, random, markdown, re
from bs4 import BeautifulSoup

from easy_thumbnails.fields import ThumbnailerImageField

from easy_thumbnails.files import get_thumbnailer

from djangoratings.fields import VotingField, FavoriteField

def generate_sha1(string, salt=None):
    if not salt:
        salt = sha_constructor(str(random.random())).hexdigest()[:5]
    hash = sha_constructor(salt+str(string)).hexdigest()

    return (salt, hash)

def make_upload_path(instance, filename):
    extension = filename.split('.')[-1].lower()
    salt, hash = generate_sha1(instance.id)
    return '%(path)s%(hash)s.%(extension)s' % {'path': 'upload/',
                                               'hash': hash[:10],
                                               'extension': extension}

class Blog(models.Model):
    """Blog model."""
    title = models.CharField(_('title'), max_length=100)
    slug = models.SlugField(_('slug'), unique=True)
    is_delete = models.BooleanField(_('is delete'), default=False)
    description = models.TextField(_('description'), blank=True)
    description_html = models.TextField(_('description html'), blank=True, null=True)
    created = models.DateTimeField(_('created'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)
    owner = models.ForeignKey(User)
    group = models.ForeignKey(Group, blank=True, null=True, related_name='group_blog')
    favorite = FavoriteField()

    class Meta:
        verbose_name = _('blog')
        verbose_name_plural = _('blogs')
        ordering = ('title',)
        permissions = (
                ('add_post_blog', 'Can add post to blog'),
            )

    def __unicode__(self):
        return u'%s by %s' % (self.title, self.owner)
        
    @permalink
    def get_absolute_url(self):
        return ('blog_detail', None, {'blog_slug': self.slug})
        
    def get_posts_count(self):
        return Post.objects.published().filter(blog=self).count()

    def save(self, *args, **kwargs):
        self.description_html = markdown.markdown(self.description, extensions=['nl2br', ])
        super(Blog, self).save(*args, **kwargs)

class Category(models.Model):
    """Category model."""
    blog = models.ForeignKey(Blog, related_name='blog_categories', help_text=u'Адрес, по которому будет доступна данная категория.')
    title = models.CharField(_('title'), max_length=100)
    slug = models.SlugField(_('slug'))

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')
        unique_together = ("slug", "blog")
        ordering = ('title',)

    def __unicode__(self):
        return u'%s' % (self.title)
        
    @permalink
    def get_absolute_url(self):
        return ('blog_category_detail', None, {'blog_slug': self.blog.slug ,'slug': self.slug})

    def get_posts_count(self):
        return Post.objects.published().filter(categories=self, is_delete = False).count()

class Post(models.Model):
    """Post model."""
    STATUS_CHOICES = (
        (1, _('Draft')),
        (2, _('Public')),
    )
    title = models.CharField(_('title'), max_length=200)
    author = models.ForeignKey(User)
    blog = models.ForeignKey(Blog, related_name='posts')
    body = models.TextField(_('body'), )
    body_html = models.TextField(_('body html'), blank=True, null=True)
    body_anons = models.TextField(_('body anons'), blank=True, null=True)
    body_html_anon = models.TextField(_('body html for anon'), blank=True, null=True)
    body_anons_anon = models.TextField(_('body anons for anon'), blank=True, null=True)
    status = models.IntegerField(_('status'), choices=STATUS_CHOICES, default=2)
    allow_comments = models.BooleanField(_('allow comments'), default=True)
    is_delete = models.BooleanField(_('is delete'), default=False)
    publish = models.DateTimeField(_('publish'), default=datetime.datetime.now)
    created = models.DateTimeField(_('created'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)
    categories = models.ManyToManyField(Category, blank=True)
    tags = TagField()
    favorite = FavoriteField()
    rating = VotingField()
    objects = PublicManager()

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')
        db_table  = 'blog_posts'
        ordering  = ('-publish',)
        get_latest_by = 'publish'

    def __unicode__(self):
        return u'%s' % self.title

    @permalink
    def get_absolute_url(self):
        return (
            'post_detail', 
            None, 
            {
                'blog_slug': self.blog.slug,
                'pk': self.pk,
            }
        )

    def get_previous_post(self):
        try:
            post = self.get_previous_by_publish(status__gte=2, blog=self.blog, is_delete=False)
        except Post.DoesNotExist:
            return False
        else:
            return post

    def get_next_post(self):
        try:
            post = self.get_next_by_publish(status__gte=2, blog=self.blog, is_delete=False)
        except Post.DoesNotExist:
            return False
        else:
            return post

    def save(self, *args, **kwargs):
        html = self.body
        myre = re.compile(ur'\[cut(=?[^\]]*)\]', re.UNICODE)
        result = myre.split(html)
        
        anons = result[0]
        html = ''.join(result)

        spoiler1 = re.compile(ur'\[spoiler\]', re.UNICODE)
        spoiler2 = re.compile(ur'\[/spoiler\]', re.UNICODE)
        
        anons = spoiler1.sub(u'<span class="splr">', anons)
        anons = spoiler2.sub(u'</span>', anons)

        html = spoiler1.sub(u'<span class="splr">', html)
        html = spoiler2.sub(u'</span>', html)

        self.body_anons = markdown.markdown(anons, extensions=['nl2br', ])
        self.body_html = markdown.markdown(html, extensions=['nl2br', ])

        soup_b = BeautifulSoup(self.body_html, "html.parser")
        imgs_b = soup_b.find_all('img')

        for img in imgs_b:
            if not img['src'].startswith('http://'):
                file_img = img['src'].replace(settings.MEDIA_URL, '', 1)
                try:
                    obj_img = Image.objects.get(file=file_img)
                    if img.parent.name != 'a' and not img['src'].endswith('.gif'):
                        thumb = get_thumbnailer(obj_img.file)['post']
                        img['src'] = thumb.url
                        img.wrap(soup_b.new_tag("a", href=obj_img.file.url))
                except:
                    pass

        self.body_html = soup_b.prettify()

        soup_a = BeautifulSoup(self.body_anons, "html.parser")
        imgs_a = soup_a.find_all('img')

        for img in imgs_a:
            if not img['src'].startswith('http://'):
                file_img = img['src'].replace(settings.MEDIA_URL, '', 1)
                try:
                    obj_img = Image.objects.get(file=file_img)
                    if img.parent.name != 'a' and not img['src'].endswith('.gif'):
                        thumb = get_thumbnailer(obj_img.file)['post']
                        img['src'] = thumb.url
                        img.wrap(soup_a.new_tag("a", href=obj_img.file.url))
                except:
                    pass

        self.body_anons = soup_a.prettify()

        super(Post, self).save(*args, **kwargs)

class Image(models.Model):
    file = ThumbnailerImageField(_('file'), upload_to=make_upload_path,)
    created = models.DateTimeField(_('created'), auto_now_add=True)
    user = models.ForeignKey(User)
    post = models.ForeignKey(Post, blank=True, null=True)
    is_delete = models.BooleanField(_('is delete'), default=False)
    in_use = models.BooleanField(_('in use'), default=False)

    class Meta:
        verbose_name = _('image')
        verbose_name_plural = _('images')
        ordering  = ('-created',)
        get_latest_by = 'created'

    def get_delete_url(self):
        return reverse('blog_del_image', args=[self.id,])

    def __unicode__(self):
        return u'%s' % self.file

templates/_pagination.html
{% load i18n %}{% spaceless %}
<div class="pagination pagination-small pagination-centered">
    <ul>
    {% if page_obj.has_previous %}
        <li><a href="{{baseurl}}page-{{ page_obj.previous_page_number }}/" class="prev">&lsaquo;&lsaquo;</a></li>
    {% else %}
        <li class="disabled"><a href="#">&lsaquo;&lsaquo;</a></li>
    {% endif %}
    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active"><a href="#" class="current page">{{ page }}</a></li>
            {% else %}
                <li><a href="{{baseurl}}page-{{ page }}/" class="page">{{ page }}</a></li>
            {% endifequal %}
        {% else %}
            <li class="disabled"><a href="#">...</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li><a href="{{baseurl}}page-{{ page_obj.next_page_number }}/" class="next">&rsaquo;&rsaquo;</a></li>
    {% else %}
        <li class="disabled"><a href="#">&rsaquo;&rsaquo;</a></li>
    {% endif %}
    </ul>
</div>{% endspaceless %}

templates/base-1c.html
{% extends "body.html" %}

{% block body %}
        <div class="row-fluid">
			<div class="span12">
            	{% block content_title %}{% endblock %}
            	<div class="wrcnt">{% block content %}{% endblock %}</div>
        	</div>
        </div>
{% endblock %}

templates/base.html
{% extends "body.html" %}

{% block body %}
    <div class="row-fluid">
        <div class="span3 pull-right" >
			<form action="/search/" method="get" id="post_form" class="form-search" >
				<input type="text" class="input-medium search-query span10" name="q" value="{{form.q.value}}" />
				<button type="submit" class="btn"><i class="icon-search"></i></button>
			</form>
            {% block right-block %}{% endblock %}
            <ul class="nav nav-list">
              {% if user.is_authenticated %}
                {% load umessages_tags thumbnail %}{% get_unread_message_count_for user as message_count %}
                <li class="nav-header">
                    <a class="pull-right" href="{% url userena_signout %}"><i class="icon icon-off"></i></a>
                    <a href="{% url userena_profile_detail user.username %}">
                        <img src="{{user.profile.mugshot|thumbnail_url:'small'}}" class="profileicon" /> {{ user.username }}
                    </a>
                </li>
                
                <li><a href="{% url userena_umessages_list %}">Сообщения{% if message_count %} <span class="badge badge-important">{{ message_count }}</span>{% endif %}</a></li>
                {% if user.is_superuser %}<li><a href="/admin/">Админка</a></li>{% endif %}

                <li class="nav-header">
                    <a class="pull-right" href="{% url blog_form_add %}" title="Добавить блог"><i class="icon icon-plus"></i></a>
                    Мои блоги
                </li>
                {% load blog %}
                {% get_user_blogs user as blog_list %}
                    {% for blog in blog_list %}
                        <li><a href="{% url blog_detail blog.slug %}">{{blog.title}}</a></li>
                    {% endfor %}
            {% else %}
                <li><a href="{% url userena_signin %}">Вход</a></li>
            {% endif %}
            </ul>
            <hr/>
            <div class="well well-small hidden-phone" >
                {% if online_users %}
                    <p>Сейчас на сайте:<br/>
                        {% for ua in online_users %}
                            <a href='{% url userena_profile_detail ua.user.username %}'>{% if ua.user.get_full_name %}{{ ua.user.get_full_name }}{% else %}{{ ua.user.username }}{% endif %}</a>{%  if not forloop.last %},{% endif %}
                        {% empty %}
                            Никого :(
                        {% endfor %}
                    </p>
                {% endif %}
                {% if today_online_users %}
                    <p>За последние 24 были:<br/>
                    {% for ua in today_online_users %}
                        <a href='{% url userena_profile_detail ua.user.username %}'>{% if ua.user.get_full_name %}{{ ua.user.get_full_name }}{% else %}{{ ua.user.username }}{% endif %}</a>{%  if not forloop.last %},{% endif %}
                    {% empty %}
                        Никого :(
                    {% endfor %}
                    </p>
                {% endif %}
            </div>
            {% load tagging_tags %}
            {% tags_for_model blog.post as widget_tags with counts %}
            {% for tag in widget_tags|dictsortreversed:"count"|slice:":30" %}
                <a class="label label-info" href="{% url blog_tag_detail tag.id %}" title="{{ tag.name }}">{{ tag.name }}</a>
            {% endfor %}
        </div>
        <div class="span9 no-margin-left">
            {% block content_title %}{% endblock %}
            <div class="wrcnt">{% block content %}{% endblock %}</div>
        </div>
    </div>
{% endblock %}

templates/comment.html
{% load markup thumbnail blog ratings humanize %}

{% if comment.is_public %}
<div class="comment item" id="c{{comment.id}}">
    <p class="name">
        {% if comment.user %}
            <a href='{% url userena_profile_detail comment.user.username %}'>{{comment.user.profile.get_full_name_or_username }}</a>
        {% else %}
            Аноним
        {% endif %}
        написал{% if user.profile.gender == 2 %}a{% endif %}
        <abbr title="{{comment.submit_date|date:"d.m.Y H:i"}}">{{ comment.submit_date|naturaltime }}</abbr>,
        <a name="c{{ comment.id }}" href="{{ comment.get_absolute_url }}" class="count">#{{comment.id}}</a>
        {% if comment.parent and not comment.parent.is_removed %}
            ответ на <a href="{{ comment.parent.get_absolute_url }}" class="count">#{{comment.parent.id}}</a>
        {% endif %}
        {% if index %}
            <br/>в блоге <a href='{{ comment.content_object.blog.get_absolute_url }}'>{{ comment.content_object.blog.title|truncatewords:"10" }}</a>
            на запись <a href='{{ comment.content_object.get_absolute_url }}'>{{ comment.content_object.title|truncatewords:"10" }}</a>
        {% endif %}
    </p>
    {% if not index and user.is_authenticated %}
        <a href="#" class="addansw">ответить</a>
        <a href="#" class="delansw">не отвечать</a>
    {% endif %}
    <div class="commenticon{% if comment.user.useractivity.is_online %} online{% endif %}">
    {% if comment.user %}
        <img src="{{comment.user.profile.mugshot|thumbnail_url:'tocomment'}}" alt="{{ comment.user.profile.get_full_name_or_username }}" />
    {% endif %}
    </div>
    <div class="commentbody" >
        {{ comment.comment_html|safe|hide_text:user}}
    </div>
    <div class="vote">{% rating_widget on comment.rating %}</div>
    <div class="clearfix"></div>
    {% if user == comment.user and comment.get_editable %}
    <div class="edit">
        <a class="edit-url" href="#edit{{ comment.id }}" data-url="{% url blog_edit_comment comment.id %}">редактировать</a> |
        <a class="delete-url" href="#delete{{ comment.id }}" data-url="{% url blog_del_comment comment.id %}">удалить</a>
    </div>
    {% endif %}
</div>
{% endif %}

templates/comments_list.html
{% extends "base.html" %}

{% block title %}Свежие комменатрии{% endblock %}

{% block li-comments %}active{% endblock %}

{% block content_title %}
        <h1>Свежие комментарии в блогах</h1>
{% endblock %}


{% block content %}
    {% for comment in object_list %}
        {% include 'comment.html' with index='1' %}
    {% endfor %}

    {% if is_paginated %}
            {% url comments_all as baseurl %}
            {% include "_pagination.html" with baseurl=baseurl %}
    {% endif %}

{% endblock %}


{% block js %}
    <script type="text/javascript" >
        {% for comment in object_list %}{% if comment.parent %}
                var respdiv = $('#{{ comment.parent.id }} .response');
                if (respdiv.length == 0) {
                    $('#{{comment.parent.id}}').append('<div class="response">Ответы: </div>');
                    respdiv = $('#{{ comment.parent.id }} .response');
                };
                respdiv.append('<a href="{{ comment.get_absolute_url }}" >>>{{comment.id}}</a>, ');
        {% endif %}{% endfor %}
    </script>
{% endblock %}

templates/field.html
{% if not field.is_hidden %}    
<div class="control-group{% if field.errors %} error{% endif %}" id="field_{{ field.html_name }}">
    {% if field.name != "body" %}
    <label class="control-label {% if field.field.required %} required{% endif %}" for="id_{{field.name}}">{{ field.label }}</label>
    {% endif %}
    <div class="controls">
        {{ field }}
        {% if field.help_text %}
            <p class="help-block">{{ field.help_text|safe }}</p>
        {% endif %}
        {% if field.errors %}
            <span class="help-inline">{{ field.errors }}</span>
        {% endif %}
    </div>
</div>
{% else %}
{{ field }}
{% endif %}

templates/index.html
{% extends "base.html" %}

{% block title %}Система блогов и не только{% endblock %}

{% block li-index %}active{% endblock %}

{% block content_title %}{% endblock %}

{% block content %}
    <div class="list post_list">
        {% for post in posts %}
            {% include 'blog/post.html' with post=post %}
        {% endfor %}
    </div>
{% endblock %}

templates/sample_tree.html
{% load threadedcomments_tags %}

{% for comment in comment_list|fill_tree|annotate_tree %}

{% ifchanged comment.parent_id %}{% else %}
    </li>
{% endifchanged %}

{% if not comment.open and not comment.close %}
    </li>
{% endif %}
    
{% if comment.open %}
    <ul>
{% endif %}

<li{% if comment.last %} class="last"{% endif %}>

{{ comment.tree_path }}{% if comment.added_path %} ADDED {% endif %}

{% for close in comment.close %}
    </li>
    </ul>
{% endfor %}

{% endfor %}

templates/wall.html
{% load markup thumbnail blog ratings humanize %}

    <div class="wall item" id="c{{comment.id}}">
        <p class="name">
            {% if comment.user %}
                <a href='{% url userena_profile_detail comment.user.username %}'>{{comment.user.profile.get_full_name_or_username }}</a>
            {% else %}
                Аноним
            {% endif %}
            написал{% if user.profile.gender == 2 %}a{% endif %}
            <abbr title="{{comment.submit_date|date:"d.m.Y H:i"}}">{{ comment.submit_date|naturaltime }}</abbr>
            {% if index %}
                {% if comment.content_type.name == 'group' and comment.content_object %}
                    <br/>в группе <a href='{{ comment.content_object.get_absolute_url }}'>{{ comment.content_object.title|truncatewords:"10" }}</a>
                {% endif %}
                {% if comment.content_type.name == 'user' and comment.content_object %}
                    <br/>в профиле <a href='{% url userena_profile_detail comment.content_object.username %}'>{{ comment.content_object.profile.get_full_name_or_username|truncatewords:"10" }}</a>
                {% endif %}

            {% endif %}
        </p>
        <div class="commenticon{% if comment.user.useractivity.is_online %} online{% endif %}">
            {% if comment.user %}
                <img src="{{comment.user.profile.mugshot|thumbnail_url:'tocomment'}}" alt="{{ comment.user.profile.get_full_name_or_username }}" />
            {% endif %}
        </div>
        <div class="commentbody" >
            {{ comment.body_html|safe }}
        </div>
        <div class="vote">{% rating_widget on comment.rating %}</div>
        <div class="clearfix"></div>
        {% if user == comment.user and comment.get_editable %}
            <div class="edit">
                <a class="edit-url" href="#edit{{ comment.id }}" data-url="{% url wall_edit_comment comment.id %}">редактировать</a> |
                <a class="delete-url" href="#delete{{ comment.id }}" data-url="{% url wall_del_comment comment.id %}">удалить</a>
            </div>
        {% endif %}
    </div>

templates/wall_item_list.html
{% extends "base.html" %}

{% block title %}Свежие записи на стенах{% endblock %}

{% block li-walls %}active{% endblock %}

{% block content_title %}
    <h1>Свежие записи на стенах</h1>
{% endblock %}


{% block content %}
        {% for comment in object_list %}
            {% include 'wall.html' with index='1' %}
        {% endfor %}

    {% if is_paginated %}
        {% url wall_items_all as baseurl %}
        {% include "_pagination.html" with baseurl=baseurl %}
    {% endif %}

{% endblock %}